# Generated by Django 5.0 on 2023-12-28 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2023, 12, 28)),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
