# Generated by Django 5.0 on 2023-12-28 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_aluno_data_nascimento_alter_aluno_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
